Testing models
justynaadam/ticket_app pull request #1
Opened 2017-07-10 21:06 UTC by justynaadam

2017-07-11 20:59 UTC, kulisz commented on spec/factories/tickets.rb
> +	title 'Lorem ipsum'
zamiast hardkodowanego tekstu możesz użyć gemu https://github.com/stympy/faker do generowaniu rożnych nazw

2017-07-11 21:03 UTC, kulisz commented on spec/models/category_spec.rb
> +
dopisz sprawdzenie czy relacje są poprawnie skonstruwone, przykład poniżej, i zastosować do każdego modelu gdzie są relacje
`

context 'model assiociations' do
--
  | it { should belong_to(:purchase_contractor) }
  | it { should belong_to(:sale_contractor) }
  | it { should belong_to(:auction) }
  | it { should have_many(:cart_fees) }
  | it { should accept_nested_attributes_for(:cart_fees) }
  | end

`

2017-07-11 21:11 UTC, kulisz requested changes

2017-07-11 21:11 UTC, kulisz commented on spec/models/ticket_spec.rb
> +      ticket.title = '   '
nie potrzeba wypełniać pustymi znakami wystarczy samo użycie ticket.title = '' lub nawet ticket.title = nil, 
to samo przy innych przykładach

2017-07-11 21:11 UTC, kulisz commented on spec/models/ticket_spec.rb
> +      ticket.title = 'a' * 71
za pomocą fakera(wyżej podałem) możesz wygenerować tekst o zadanej długości :)

2017-07-11 21:11 UTC, kulisz commented on spec/factories/tickets.rb
> +	title 'Lorem ipsum'
zamiast hardkodowanego tekstu możesz użyć gemu https://github.com/stympy/faker do generowaniu rożnych nazw

2017-07-11 21:11 UTC, kulisz commented on spec/models/category_spec.rb
> +
w każdym modelu dodaj sprawdzenie czy relacje są poprawnie skonstruowane, widziałem w innym specu że tego użyłeś więc w reszcie też proszę :)

2017-07-11 21:11 UTC, kulisz commented on spec/models/search_spec.rb
> +	search = Search.new
coś chyba z wcięciami jest nie tak, upewnij się że w edytorze masz ustawione wcięcia jako spacje i ich ilość ustawiona na dwa. przeleć tak wszystkie pliki aby poprawić (w sublime w dolnym prawym rogu jest automat do tego)

2017-07-13 07:41 UTC, kulisz commented
@justynaadam rzeczy z tego pr chyba są w tym drugim pr. Czy tworząć branch dla drugiego pr utworzyłaś go od tego brancha czy od mastera?

2017-07-13 10:45 UTC, merged

2017-07-13 13:54 UTC, justynaadam commented
@kulisz od mastera