Testing controllers and models
justynaadam/ticket_app pull request #2
Opened 2017-07-11 12:18 UTC by justynaadam

2017-07-11 21:25 UTC, kulisz requested changes
ogólnie spoko, trzymaj tak dalej!

2017-07-11 21:25 UTC, kulisz commented on spec/controllers/categories_controller_spec.rb
> +  	before(:each) { @category = create(:category) }
@category = create(:cat...) przenieś do pierwszego it'a bo tam tylko sprawdzasz kategorie więc nie ma potrzeby generować tego dla każdego it'a

2017-07-11 21:25 UTC, kulisz commented on spec/controllers/relationships_controller_spec.rb
> +    before(:each) { @relationship = create(:relationship) }
jw, przenieść do it'a gdzie jest wymagange

2017-07-11 21:25 UTC, kulisz commented on spec/controllers/searches_controller_spec.rb
> +  	before(:each) { @search = Search.create() }
wciecia

2017-07-11 21:25 UTC, kulisz commented on spec/controllers/static_pages_controller_spec.rb
> +  	it 'render the help template' do
wciecia

2017-07-11 21:25 UTC, kulisz commented on spec/controllers/tickets_controller_spec.rb
> +      before(:each) do
przed before let(:user) { create(:user, email: 'foo@bar11.co') }
a gdzie wcześniej uzyte zostało @user wystarczy uzyc samo user

2017-07-11 21:25 UTC, kulisz commented on spec/controllers/tickets_controller_spec.rb
> +	 #  describe 'POST #create' do
do usunięcia jeśli nie będzie do odkomentowania

2017-07-12 13:44 UTC, justynaadam commented
@kulisz kod jest gotowy do ponownego sprawdzenia

2017-07-13 07:46 UTC, kulisz approved these changes
Jeśli wszystkie testy przepisałaś to teraz możesz zacząć rozszerzać istniejące o dodatkowe. Do tego możesz użyć gemu https://github.com/colszowka/simplecov który wskaże pokrycie testami Twojej aplikacji i na tej podstawie możesz dopisywać nowe testy :)

2017-07-13 10:45 UTC, merged

2017-07-13 13:45 UTC, justynaadam commented
@kulisz jeszcze tylko features specs zostały mi do przepisania - jutro rano zrobie pull request ;)